# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sociast' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sociast

	pod ‘Firebase/Core’
	pod ‘Firebase/AdMob’

  target 'SociastTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SociastUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
