# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ninjabolt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ninjabolt

	pod ‘Firebase/Core’
	pod ‘Firebase/AdMob’

  target 'NinjaboltTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NinjaboltUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
